name: Fetch and Publish

on:
  workflow_dispatch:         # run it manually
  schedule:
    - cron: "0 * * * *"      # hourly

permissions:
  contents: write            # allow committing updated files

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node 18
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Install deps
        run: npm install

      - name: Run fetch script
        run: node index.js

      - name: Commit updated data
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add docs/data.json docs/digest.html
          git commit -m "Update data [skip ci]" || echo "No changes"
          git push
